site_name: Molecular Dynamics Blog
site_author: Shaunak Badani
site_description: A blog that helps break down Molecular Dynamics and statistical mechanics concepts into simpler, byte-sized nuggets of information.
site_url: https://shaunak-badani.github.io/MDBlog
theme:
  name: material
  logo: assets/md_scenario_icon.png
  features:
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shaunak-badani
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shaunak-badani-b70b88176/

copyright: Copyright &copy; 2025 Shaunak Badani
    

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js